apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-system-server-certs-admin-secret-manager
  namespace: kube-system
subjects:
- kind: User
  name: system:serviceaccount:kube-system:server-certs-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: kube-system-secrets-manager
  apiGroup: rbac.authorization.k8s.io
